### ISSUE TITLE
Is reviewer-added events supported by its-base plugin?

### ISSUE THREAD

**Issue by PandyTheBroh** [GerritCodeReview/plugins_its-base#1]
Hello.

I'm not sure if this is the correct place to ask this question. If I'm wrong, please, tell me where I can ask it.

In my team we are using Gerrit with several plugins. One of them _is its-jira_; it is a its-base-based plugins.
One of the configurations that we have setted for this plugin is handle the _reviewer-added_ event. But since a time ago this action doesn't work. I'm pretty sure that the configuration is correct mainly cause in the past it worked.

After of a investigation I have checked that _reviewer-added_ is a supported _gerrit stream-events_ but at the same time the documentation of its-base events doesn't mention it.

Could you confirm me if its-base plugin has support to handle the _reviewer-added_ event?

Like reference I share the configuration of these plugins in our gerrit:

```
#############
gerrit.config
#############
...
[plugin "its-jira"]
        enabled = true
        association = SUGGESTED

[commentLink "its-jira"]
        match = ([A-Z]+-[0-9]+)
        html = <a href=\"https://bla.bla.bla.com/browse/$1\">$1</a>

[its-jira]
        url = https://bla.bla.bla.com
        username = blablabla
...
##################
its/actions.config
##################
...
[rule "merged"]
        event-type = change-merged
        action = add-velocity-comment Merged

[rule "revieweradd"]
        event-type = reviewer-added
        action = add-velocity-comment Reviewer
...

```

Thank you very much.

**Comment by lucamilanesio** [comment]
@PandyTheBroh the right place to ask questions is the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss).

**Comment by PandyTheBroh** [comment]
Ok. Thank you @lucamilanesio.
